# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('openId', models.CharField(max_length=50, unique=True, verbose_name='openId')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.IntegerField(default=1)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('tel', models.CharField(blank=True, max_length=12)),
                ('avatar', models.ImageField(default='photo/default.png', max_length=256, upload_to='photo')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
