# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170909_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_amount',
            new_name='goods_amount',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_price',
            new_name='goods_price',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='api.Order'),
        ),
    ]
