# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170909_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsimage',
            old_name='iamge',
            new_name='image',
        ),
    ]
