# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170914_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['-update_at']},
        ),
        migrations.AlterField(
            model_name='classify',
            name='remark',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='api.Goods'),
        ),
    ]
