# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170918_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['create_at']},
        ),
        migrations.RenameField(
            model_name='address',
            old_name='creat_at',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='creat_at',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='classify',
            old_name='creat_at',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='creat_at',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='goodsimage',
            old_name='creat_at',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='creat_at',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='creat_at',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='creat_at',
            new_name='create_at',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set([('goods', 'user')]),
        ),
    ]
