# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170918_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='mainImage',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
