# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_cartitem_selected'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swiper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='swiper')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swiper', to='api.Goods')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
