# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20171026_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, '\u5f85\u4ed8\u6b3e'), (2, '\u5f85\u53d1\u8d27'), (3, '\u5f85\u6536\u8d27'), (4, '\u5df2\u6536\u8d27'), (5, '\u552e\u540e')], default=1, verbose_name='\u8ba2\u5355\u72b6\u6001'),
        ),
    ]
